### ISSUE TITLE
background

### ISSUE THREAD

**Issue by Nick-Rowland** [Yerren/FreshWDL#11]
Hi Yerren,

Great project and is working well for me except the background. My web site needs an opaque background for WDL (like the original WDL) otherwise the site shows through the new WDL page. I've got round the issue by linking to a new page without a menu system but would prefer not to have to do that.

Also, for the future, would it be possible to choose the type of gauge? I prefer dials for wind speed etc but realise this is purely personal.

Keep up the good work,

Cheers
Nick

**Comment by Yerren** [comment]
Hey Nick,

Could you give me a link to your site, and where you would want the transparent background so I can check it out in more detail? We might be able to figure out a quick fix.

It is the plan to be able to customise your page with gauge choices like that in the future, but it is in the _distant_ future, as there are many things which still need to be implemented before we can look at making more options of the things that already exist 😃

-Yerren

**Comment by Nick-Rowland** [comment]
Hi Yerren,

Sure the links are below, I need the background to be white or a colour (similar to WDL) rather than transparent. If you look at this link the FWDL display shows the site background through it which makes it hard to read.
http://www.sunwharf.com/willingdon/fwdl.html

The original flash WDL version of the page does not do this http://www.sunwharf.com/willingdon/wdl.html

I have worked round the issue by linking direct to FWDL like this http://www.sunwharf.com/willingdon/live.html but it's not ideal and prefer to have the menu options showing.

Thanks for your help
Cheers
Nick

**Comment by Yerren** [comment]
Hey,

Probably the easiest way to achieve this is to go to the HTML code of your page, and add: 
`style="background-color: white;"`
to the opening iframe tag, such as:
`<iframe src="live.html" scrolling="no" style="background-color: white;" width="800" height="600" frameborder="0">`

Hope this helps,
-Yerren

**Comment by Nick-Rowland** [comment]
Great thanks Yerren, that is ideal thank you

Cheers
Nick
