### ISSUE TITLE
was this accidentally left in?

### ISSUE THREAD

**Issue by quixand** [Yerren/FreshWDL#16]
https://github.com/Yerren/FreshWDL/blob/8e577b8a268c48233a594bb8ef3e6a7ef49ddbd1/css/stylesheet01.css#L224

background: #fff url("http://app.actmapi.act.gov.au/Html5Viewer260/Resources/Images/Icons/arrow-down-small-24.png") no-repeat 90% 50%;

??

**Comment by Yerren** [comment]
I believe it is there to display the "drop down" arrow for the select menu (when you have the graph or record pop-up open). From memory, it might not display properly on all browsers though.

You can see the arrow (more of a triangle, really) in this screen shot: https://puu.sh/AdfhK/8192ff9623.png

Hopefully that helps.

**Comment by quixand** [comment]
ok, would it not be better to include the image in the repository? seems a little brittle referencing another domain thats outside of the implementers control.

**Comment by Yerren** [comment]
That seems like a good idea, and honestly should have been done a long time ago.
Cheers.
