### ISSUE TITLE
Mobile Friendly View

### ISSUE THREAD

**Issue by buzz-kill** [Yerren/FreshWDL#17]
Love. Love. Love. The new option.
Would like a mobile friendly view. It does not really frame correctly on mobile screens, or work properly when transitioning between portrait and landscape.
Would like to additional sensor support like the new purple air sensors now supported in WD.
Would like to include a local radar image.

**Comment by Yerren** [comment]
Glad to hear it!

Currently, the idea is just that it does display at all on mobile!
In the (distant) future I would like to make a bit of a more organised view for mobile possible (different pages possibly.)
As for other sensors, slowly they will be added, but it is a very slow process, as I can only dedicate significant amounts of time to it during the period between semesters of my study (so only twice a year!).

I appreciate your feedback, and will add notes to the project's to do list (the full list can be seen under the "projects" tab above).

**Comment by Yerren** [comment]
Additionally, could you describe in more detail what happens when changing between landscape and portrait? I thought that all issues around it had been solved, so would really appreciate details so I can fix what is happening!
