### ISSUE TITLE
Internet Explorer /  Edge Issues loading FreshWDL

### ISSUE THREAD

**Issue by aceycv8** [Yerren/FreshWDL#39]
Hi,

I seem to be having issues with FreshWDL loading with internet explorer both with Edge and Internet explorer.
it just sits at Collecting Data...
when i run the console to debug i get the following:

![image](https://user-images.githubusercontent.com/28552756/78326333-b6ce0080-75ac-11ea-98cb-b3932b529bcd.png)

Can you please assist?

Thank you

**Comment by aceycv8** [comment]
After doing some more looking i've found it's an issue with gitcdn
i've downloaded your project and put it into my webserver and edited out all the gitcdn urls to point to my web server direct for now until it gets resolved,

meaning no updates but atleast the site now works

![image](https://user-images.githubusercontent.com/28552756/78412378-b3d31e80-7645-11ea-854f-1668778deb64.png)

**Comment by Yerren** [comment]
This is strange, as I can still connect to GitCDN on my end.
If you put up your site again with the GitCDN urls, let me know, and I'll check it out.

**Comment by aceycv8** [comment]
unfortunately i can't put the site we use on the public web due to it being a business, however if i click on the gitcdn links i get the following errors

![image](https://user-images.githubusercontent.com/28552756/78415586-344d4b80-7655-11ea-95f3-3669eff80dd8.png)

**Comment by Yerren** [comment]
No worries, I understand. If your site is not on the public web is it possible this is causing the issues?
I probably cannot be of any more help without seeing what's going on first hand, sorry!

**Comment by aceycv8** [comment]
That's alright Yerren, 
I've got the work around for now that works for us by making those files local on our own web server.
It's just starage it's started to happen as I've been using your FreshWDL for quite a while now.

i've tested the gitcdn site from my own home internet connection and i get the same error as the screen shot posted above so that was ruling out anything blocking on our business network

**Comment by Yerren** [comment]
That's very strange. Seems to be working here. Can you double check that this link doesn't work for you:
https://gitcdn.xyz/cdn/Yerren/FreshWDL/master/js_bundles/moment-with-locales.min.js
Thanks!

**Comment by aceycv8** [comment]
nope - that link does work - i get presented with this error
![image](https://user-images.githubusercontent.com/28552756/78416570-1c2cfa80-765c-11ea-8f60-761afc6b0b5c.png)
