### ISSUE TITLE
Fixing time display

### ISSUE THREAD

**Issue by ausfestivus** [Yerren/FreshWDL#40]
Afternoon,

Just looking for some help to get the time display sorted out.
https://weather.mtcolah.bestfamily.id.au/

<img width="1482" alt="Screen Shot 2020-05-31 at 4 26 44 pm" src="https://user-images.githubusercontent.com/40222285/83345943-a8f1ed00-a35b-11ea-8311-25ddd2ba7f4c.png">

You can see the correct local time in the header on the left. The time display on the right is incorrect. Obviously related to some timezone config in the underlying webhost (Ubuntu 16.04, Apache 2).

The odd thing is though it doesnt feel like a TZ config problem on the host because the time that FreshWDL displays isnt actually UTC. UTC is currently:

```bash
ubuntu@jump00:~$ date -u
Sun May 31 06:29:01 UTC 2020
```

**Comment by Yerren** [comment]
Hi,

So, to clarify, are you saying the sun and moon rise/set are incorrect, but the header time (on the left) is correct?

There are a some time zone conversions happening in the background, so it is very possible something has gone wrong there.

**Comment by ausfestivus** [comment]
> So, to clarify, are you saying the sun and moon rise/set are incorrect, but the header time (on the left) is correct?

Correct. The Sun does not rise at 0259 in Sydney Australia. I havent validate the displayed Moon times myself.

If you compare the times on http://weather.coachdrive.info/ with mine they are different. I dont understand why. FW2278 is in Sydney also so I would expect my times to be almost identical to those.

**Comment by Yerren** [comment]
I'll check it out when I have the time, I can only imagine it is some side effect of an "automatic" time zone conversion. Thanks for the heads up!

**Comment by ausfestivus** [comment]
Just FYI, the historical data reset I did in https://github.com/Yerren/FreshWDL/issues/41 has not fixed this issue.
The LAT and LONG in my data is correct.

If you want any other information about the setup let me know what you need and the best way to get it to you directly.

**Comment by ausfestivus** [comment]
Another FYI. Ive been working on getting the Saratoga PHP stuff up and running as well. I don't have a public site available yet however the same time display problem occurs in it as well.

<img width="174" alt="Screen Shot 2020-07-06 at 4 28 47 pm" src="https://user-images.githubusercontent.com/40222285/86562275-c7c05080-bfa5-11ea-954c-1b2e593cc0b5.png">

**Comment by ausfestivus** [comment]
I finally managed to track the root cause of this problem down. Found the answer in https://www.weather-watch.com/smf/index.php/topic,71087.0.html

My consolewd Longitude setting wasnt a negative number. Added the - to the value and the freshwdl display is now good.
