### ISSUE TITLE
Pure HTML/CSS for responsive sizing and layout

### ISSUE THREAD

**Issue by digizimm** [Yerren/FreshWDL#42]
I was requested to remove the graphs and show them in a separate Layout instead.
Since everything responsive is done with Javascript, i had quite trouble and a bad experience adjusting
the dashboard for that request. I am curious why one would decide to handle responsiveness with Javascript
instead for example with Flexboxes and relative Dimensions?

**Comment by Yerren** [comment]
Honestly, when I started this project, I was only expecting it to be used by a single person (my father). I had zero JS (and only minimal HTML/CSS) experience, so there is a lot going on that can be attributed to naivety. I think the main factor was resizing the gauges etc. so they scaled with the view-port and, at the time, I settled on doing the scaling within the JS code.

In the back of my mind I have wanted to revamp the layout system to make it easily customisable, but... I haven't had the free time to do so, unfortunately.

I'm always open to suggestions/help, though!

**Comment by digizimm** [comment]
> 
> 
> Honestly, when I started this project, I was only expecting it to be used by a single person (my father). I had zero JS (and only minimal HTML/CSS) experience, so there is a lot going on that can be attributed to naivety. I think the main factor was resizing the gauges etc. so they scaled with the view-port and, at the time, I settled on doing the scaling within the JS code.
> 
> In the back of my mind I have wanted to revamp the layout system to make it easily customisable, but... I haven't had the free time to do so, unfortunately.
> 
> I'm always open to suggestions/help, though!

Ok, i understand. Reasonable. 
I'am waiting for client feedback to my current solution - In case there will be more layout feature request, 
i consider to develop a css-based approach for this. If it happens, i will give the repo a pull request for sure.

Best regards,
Danny

**Comment by Yerren** [comment]
If it happens, I'd love to work with you on that - even if it's just helping you navigate the code - as I am well aware the documentation is lacking...
