### ISSUE TITLE
Line charts not rendered

### ISSUE THREAD

**Issue by pilotak** [Yerren/FreshWDL#45]
What could be the reason that last 24h temperature, wind speed & barometer are not showing up? rainfall works.

http://www.infoboardrecorder.com/meteo/

**Comment by Yerren** [comment]
I've had a lot of people getting in contact with me about this problem. I've narrowed it down to an issue with the hourly date format used by some weather data upload software, and I am currently working on a fix that will hopefully be posted soon.
