### ISSUE TITLE
FreshWDL stuck at splashscreen

### ISSUE THREAD

**Issue by LondonCat** [Yerren/FreshWDL#52]
Was working OK now sticks at 'FreshWDL Collecting data ...'

**Comment by Yerren** [comment]
Could you give me the URL to your site please?

**Comment by LondonCat** [comment]
http://busza.co.uk/WDL/FreshWDLmaster.html

**Comment by Yerren** [comment]
Your clientraw.txt is blank [http://busza.co.uk/WDL/clientraw.txt](http://busza.co.uk/WDL/clientraw.txt), so I think it's a problem on the weather data upload end.

**Comment by LondonCat** [comment]
Thank you!

Sorted out and thanks for your super quick response

All the best
