### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by ausfestivus** [Yerren/FreshWDL#53]
https://weather.mtcolah.bestfamilly.id.au

Running iOS 14.4.1 on iPhone.

Site doesn't load on Safari (normal or incognito). What is displayed:
<img width="446" alt="Screen Shot 2021-03-20 at 1 45 28 pm" src="https://user-images.githubusercontent.com/40222285/111856971-89778f80-8982-11eb-86ca-533a801eb01a.png">

On Chrome on iPhone:
<img width="431" alt="Screen Shot 2021-03-20 at 1 45 50 pm" src="https://user-images.githubusercontent.com/40222285/111856977-97c5ab80-8982-11eb-912b-7952ba14a3ee.png">

A mate has said it works fine from an iPad.

**Comment by Yerren** [comment]
Try this: [](https://www.weather-watch.com/smf/index.php/topic,70957.0.html)

**Comment by ausfestivus** [comment]
Yea that fixed it. Thank you.

Maybe next time drop a pinned issue in these issues to give people some warning?
