### ISSUE TITLE
missing Semicolon in Globals.js causing SyntaxError: Unexpected identifier, cdn.jsdelivr.net delivers old / not-working Version

### ISSUE THREAD

**Issue by gunnarhaslinger** [Yerren/FreshWDL#58]
Yesterday you merged my Pull-Request https://github.com/Yerren/FreshWDL/pull/56 which fixes Globals.js causing SyntaxError: Unexpected identifier

But the Version provided via your CDN Link is still the old Version which just raises a SyntaxError:
https://cdn.jsdelivr.net/gh/yerren/FreshWDL@master/js_bundles/Globals.js

**Comment by Yerren** [comment]
Thanks for pointing that out! The cache purges automatically every so often, but I'll put a manual purge request through now. That should fix things (although you may still need to refresh your browser cache - ctrl+F5 - to see the changes).
