### ISSUE TITLE
FreshWDL-1.1.8.6a

### ISSUE THREAD

**Issue by kaarbra** [Yerren/FreshWDL#59]
FreshWDL-1.1.8.6a includes many more files than the original. Can you explain how to set up this version. Regards Kåre

**Comment by Yerren** [comment]
Hi, is there a reason that you looking to set up version 1.1.8.6a?

It's generally far easier to follow the setup instructions in the [ReadMe](https://github.com/Yerren/FreshWDL#readme), and this will mean that you are able to get automatic updates as well.

P.S.. having 1.1.8.6a listed as the "latest release" is an error on my end.

**Comment by kaarbra** [comment]
Hi Yerren,I am using your version 1.1.8.10 today. It's great that you've made an offer for those of us who used WDL.
I thought that there was a new version that could have given a few more possibilities when it comes to viewing. That's why I tried to get to what I thought was a new version. Thank you for giving me the opportunity to show the weather in a great way. Best regards, Kåre.
