### ISSUE TITLE
Last few days of 31-day Rain Graph missing

### ISSUE THREAD

**Issue by GrantKeymer** [Yerren/FreshWDL#9]
Hi Yerren,
Just a small issue I've noticed:

The last few days of the 31-day rainfall graph always show 0mm even though that certainly wasn't the case, and the 7-day graph records the rainfall correctly.  The rainfall graph on the main screen has the same issue.

Image of 31-day rainfall graph attached.

Many thanks for your efforts and keep up the good work :)

Cheers,
Grant.

![31 days rainfall](https://user-images.githubusercontent.com/35156198/34634743-de1b0890-f2eb-11e7-9190-f0be0735384c.png)

**Comment by Yerren** [comment]
Could I please get a link to your site? Seems like a peculiar issue and I'd like to be able to see what's going on in more detail.

**Comment by GrantKeymer** [comment]
Here you go Yerren:
http://www.keymer.name/weather/freshwdl.html
It is an odd one for sure.  I'm using WD for Linux (build 295) if that makes any difference.
Thanks,Grant.
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Yerren van Sint Annaland <notifications@github.com> Date: 6/01/18  2:49 PM  (GMT+12:00) To: Yerren/FreshWDL <FreshWDL@noreply.github.com> Cc: GrantKeymer <grant@keymer.name>, Author <author@noreply.github.com> Subject: Re: [Yerren/FreshWDL] Last few days of 31-day Rain Graph missing (#9) 
Could I please get a link to your site? Seems like a peculiar issue and I'd like to be able to see what's going on in more detail.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Yerren/FreshWDL","title":"Yerren/FreshWDL","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Yerren/FreshWDL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Yerren in #9: Could I please get a link to your site? Seems like a peculiar issue and I'd like to be able to see what's going on in more detail."}],"action":{"name":"View Issue","url":"https://github.com/Yerren/FreshWDL/issues/9#issuecomment-355713979"}}}

**Comment by Yerren** [comment]
I checked your clientraw files, and it seems that for some reason your 31-day rainfall graph data is four days ahead, with the four most recent days all having the value of zero (for example, the value for five days ago is what actually should be yesterday's value). The same issue seems to be present in the old WDL for you as well. It seems like this is something on the WD side of things. I would suggest asking Brian about it!

**Comment by GrantKeymer** [comment]
Thanks Yerren for looking at this so quickly.  I've emailed Brian as you suggested.
